# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory to /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Install any necessary build tools
RUN apt-get update && apt-get install -y build-essential

# Copy the C library source code to the container
COPY libsource /app/libsource

# Compile the C library
RUN cd libsource && make

# Copy the Python application code to the container
COPY app.py /app

# Run the command to start the Python application
CMD [ "python", "./app.py" ]